// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/check': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/check.get').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify.post').default>>>>
    }
    '/api/bot/report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/report.post').default>>>>
    }
    '/api/bot/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/start.post').default>>>>
    }
    '/api/bot/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/status.get').default>>>>
    }
    '/api/bot/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/stop.post').default>>>>
    }
    '/api/bot/trigger': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/trigger.post').default>>>>
    }
    '/api/delegated-owners': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delegated-owners.get').default>>>>
    }
    '/api/delegation/owners': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delegation/owners.get').default>>>>
    }
    '/api/delegation/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delegation/register.post').default>>>>
    }
    '/api/delegation/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delegation/status.get').default>>>>
    }
    '/api/errors/clear': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/errors/clear.post').default>>>>
    }
    '/api/errors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/errors/index.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/transactions/:hash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/[hash].get').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}