// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/23/2026, 7:12:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/juliuswong/dev/AavegotchiPetterUI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/plugins/**/*.{js,ts,mjs}","/Users/juliuswong/dev/AavegotchiPetterUI/composables/**/*.{js,ts,mjs}","/Users/juliuswong/dev/AavegotchiPetterUI/utils/**/*.{js,ts,mjs}","/Users/juliuswong/dev/AavegotchiPetterUI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/dev/AavegotchiPetterUI/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;