// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2026, 9:00:47 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/juliuswong/Dev/AavegotchiPetterUI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/plugins/**/*.{js,ts,mjs}","/Users/juliuswong/Dev/AavegotchiPetterUI/composables/**/*.{js,ts,mjs}","/Users/juliuswong/Dev/AavegotchiPetterUI/utils/**/*.{js,ts,mjs}","/Users/juliuswong/Dev/AavegotchiPetterUI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/juliuswong/Dev/AavegotchiPetterUI/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;